<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameserice.proto

namespace Xxgame;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TeaList extends \Google\Protobuf\Internal\Message
{
    private $tea_list;

    public function getTeaList()
    {
        return $this->tea_list;
    }

    public function setTeaList(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Xxgame\TeaInfo::class);
        $this->tea_list = $var;
    }

}

class TeaInfo extends \Google\Protobuf\Internal\Message
{
    private $tea_name = '';
    private $uid = 0;
    private $forbid = 0;
    private $msg = '';
    private $method1 = 0;
    private $type1 = 0;
    private $hall1 = '';
    private $method2 = 0;
    private $type2 = 0;
    private $hall2 = '';
    private $method3 = 0;
    private $type3 = 0;
    private $hall3 = '';
    private $tea_id = 0;

    public function getTeaName()
    {
        return $this->tea_name;
    }

    public function setTeaName($var)
    {
        GPBUtil::checkString($var, True);
        $this->tea_name = $var;
    }

    public function getUid()
    {
        return $this->uid;
    }

    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;
    }

    public function getForbid()
    {
        return $this->forbid;
    }

    public function setForbid($var)
    {
        GPBUtil::checkUint32($var);
        $this->forbid = $var;
    }

    public function getMsg()
    {
        return $this->msg;
    }

    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;
    }

    public function getMethod1()
    {
        return $this->method1;
    }

    public function setMethod1($var)
    {
        GPBUtil::checkUint32($var);
        $this->method1 = $var;
    }

    public function getType1()
    {
        return $this->type1;
    }

    public function setType1($var)
    {
        GPBUtil::checkUint32($var);
        $this->type1 = $var;
    }

    public function getHall1()
    {
        return $this->hall1;
    }

    public function setHall1($var)
    {
        GPBUtil::checkString($var, True);
        $this->hall1 = $var;
    }

    public function getMethod2()
    {
        return $this->method2;
    }

    public function setMethod2($var)
    {
        GPBUtil::checkUint32($var);
        $this->method2 = $var;
    }

    public function getType2()
    {
        return $this->type2;
    }

    public function setType2($var)
    {
        GPBUtil::checkUint32($var);
        $this->type2 = $var;
    }

    public function getHall2()
    {
        return $this->hall2;
    }

    public function setHall2($var)
    {
        GPBUtil::checkString($var, True);
        $this->hall2 = $var;
    }

    public function getMethod3()
    {
        return $this->method3;
    }

    public function setMethod3($var)
    {
        GPBUtil::checkUint32($var);
        $this->method3 = $var;
    }

    public function getType3()
    {
        return $this->type3;
    }

    public function setType3($var)
    {
        GPBUtil::checkUint32($var);
        $this->type3 = $var;
    }

    public function getHall3()
    {
        return $this->hall3;
    }

    public function setHall3($var)
    {
        GPBUtil::checkString($var, True);
        $this->hall3 = $var;
    }

    public function getTeaId()
    {
        return $this->tea_id;
    }

    public function setTeaId($var)
    {
        GPBUtil::checkUint32($var);
        $this->tea_id = $var;
    }

}

class TeaPlayerList extends \Google\Protobuf\Internal\Message
{
    private $player_list;

    public function getPlayerList()
    {
        return $this->player_list;
    }

    public function setPlayerList(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Xxgame\TeaPlayer::class);
        $this->player_list = $var;
    }

}

class TeaPlayer extends \Google\Protobuf\Internal\Message
{
    private $nickname = '';
    private $tea_id = 0;
    private $state = 0;
    private $manager = 0;
    private $numbers = 0;
    private $hall_id = 0;
    private $uid = 0;
    private $winnum = 0;
    private $remarks = '';

    public function getNickname()
    {
        return $this->nickname;
    }

    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;
    }

    public function getTeaId()
    {
        return $this->tea_id;
    }

    public function setTeaId($var)
    {
        GPBUtil::checkUint32($var);
        $this->tea_id = $var;
    }

    public function getState()
    {
        return $this->state;
    }

    public function setState($var)
    {
        GPBUtil::checkUint32($var);
        $this->state = $var;
    }

    public function getManager()
    {
        return $this->manager;
    }

    public function setManager($var)
    {
        GPBUtil::checkUint32($var);
        $this->manager = $var;
    }

    public function getNumbers()
    {
        return $this->numbers;
    }

    public function setNumbers($var)
    {
        GPBUtil::checkUint32($var);
        $this->numbers = $var;
    }

    public function getHallId()
    {
        return $this->hall_id;
    }

    public function setHallId($var)
    {
        GPBUtil::checkUint32($var);
        $this->hall_id = $var;
    }

    public function getUid()
    {
        return $this->uid;
    }

    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;
    }

    public function getWinnum()
    {
        return $this->winnum;
    }

    public function setWinnum($var)
    {
        GPBUtil::checkUint32($var);
        $this->winnum = $var;
    }

    public function getRemarks()
    {
        return $this->remarks;
    }

    public function setRemarks($var)
    {
        GPBUtil::checkString($var, True);
        $this->remarks = $var;
    }

}

class Record extends \Google\Protobuf\Internal\Message
{
    private $roomid = 0;
    private $number = 0;
    private $createtime = '';
    private $player;
    private $gametype = 0;

    public function getRoomid()
    {
        return $this->roomid;
    }

    public function setRoomid($var)
    {
        GPBUtil::checkUint32($var);
        $this->roomid = $var;
    }

    public function getNumber()
    {
        return $this->number;
    }

    public function setNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->number = $var;
    }

    public function getCreatetime()
    {
        return $this->createtime;
    }

    public function setCreatetime($var)
    {
        GPBUtil::checkString($var, True);
        $this->createtime = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Xxgame\Playerinfo::class);
        $this->player = $var;
    }

    public function getGametype()
    {
        return $this->gametype;
    }

    public function setGametype($var)
    {
        GPBUtil::checkUint32($var);
        $this->gametype = $var;
    }

}

class Single extends \Google\Protobuf\Internal\Message
{
    private $record_id = 0;
    private $createtime = '';
    private $player;
    private $index = 0;

    public function getRecordId()
    {
        return $this->record_id;
    }

    public function setRecordId($var)
    {
        GPBUtil::checkUint32($var);
        $this->record_id = $var;
    }

    public function getCreatetime()
    {
        return $this->createtime;
    }

    public function setCreatetime($var)
    {
        GPBUtil::checkString($var, True);
        $this->createtime = $var;
    }

    public function getPlayer()
    {
        return $this->player;
    }

    public function setPlayer(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Xxgame\Playerinfo::class);
        $this->player = $var;
    }

    public function getIndex()
    {
        return $this->index;
    }

    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;
    }

}

class Playerinfo extends \Google\Protobuf\Internal\Message
{
    private $nickname = '';
    private $head = '';
    private $roomcard = 0;
    private $role = 0;
    private $marquee = '';
    private $urgent = '';
    private $score = 0;
    private $uid = 0;

    public function getNickname()
    {
        return $this->nickname;
    }

    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;
    }

    public function getHead()
    {
        return $this->head;
    }

    public function setHead($var)
    {
        GPBUtil::checkString($var, True);
        $this->head = $var;
    }

    public function getRoomcard()
    {
        return $this->roomcard;
    }

    public function setRoomcard($var)
    {
        GPBUtil::checkUint32($var);
        $this->roomcard = $var;
    }

    public function getRole()
    {
        return $this->role;
    }

    public function setRole($var)
    {
        GPBUtil::checkUint32($var);
        $this->role = $var;
    }

    public function getMarquee()
    {
        return $this->marquee;
    }

    public function setMarquee($var)
    {
        GPBUtil::checkString($var, True);
        $this->marquee = $var;
    }

    public function getUrgent()
    {
        return $this->urgent;
    }

    public function setUrgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->urgent = $var;
    }

    public function getScore()
    {
        return $this->score;
    }

    public function setScore($var)
    {
        GPBUtil::checkUint32($var);
        $this->score = $var;
    }

    public function getUid()
    {
        return $this->uid;
    }

    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af2060a1067616d657365726963652e70726f746f1206787867616d6522" .
    "2c0a075465614c69737412210a087465615f6c69737418012003280b320f" .
    "2e787867616d652e546561496e666f22e2010a07546561496e666f12100a" .
    "087465615f6e616d65180120012809120b0a0375696418022001280d120e" .
    "0a06666f7262696418032001280d120b0a036d7367180420012809120f0a" .
    "076d6574686f643118052001280d120d0a05747970653118062001280d12" .
    "0d0a0568616c6c31180720012809120f0a076d6574686f64321808200128" .
    "0d120d0a05747970653218092001280d120d0a0568616c6c32180a200128" .
    "09120f0a076d6574686f6433180b2001280d120d0a057479706533180c20" .
    "01280d120d0a0568616c6c33180d20012809120e0a067465615f6964180e" .
    "2001280d22370a0d546561506c617965724c69737412260a0b706c617965" .
    "725f6c69737418012003280b32112e787867616d652e546561506c617965" .
    "72229d010a09546561506c6179657212100a086e69636b6e616d65180120" .
    "012809120e0a067465615f696418022001280d120d0a0573746174651803" .
    "2001280d120f0a076d616e6167657218042001280d120f0a076e756d6265" .
    "727318052001280d120f0a0768616c6c5f696418062001280d120b0a0375" .
    "696418072001280d120e0a0677696e6e756d18082001280d120f0a077265" .
    "6d61726b7318092001280922720a065265636f7264120e0a06726f6f6d69" .
    "6418012001280d120e0a066e756d62657218022001280d12120a0a637265" .
    "61746574696d6518032001280912220a06706c6179657218042003280b32" .
    "122e787867616d652e506c61796572696e666f12100a0867616d65747970" .
    "6518052001280d22620a0653696e676c6512110a097265636f72645f6964" .
    "18012001280d12120a0a63726561746574696d6518022001280912220a06" .
    "706c6179657218032003280b32122e787867616d652e506c61796572696e" .
    "666f120d0a05696e64657818042001280d2289010a0a506c61796572696e" .
    "666f12100a086e69636b6e616d65180120012809120c0a04686561641802" .
    "2001280912100a08726f6f6d6361726418032001280d120c0a04726f6c65" .
    "18042001280d120f0a076d617271756565180520012809120e0a06757267" .
    "656e74180620012809120d0a0573636f726518072001280d120b0a037569" .
    "6418082001280d620670726f746f33"
));

