<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userinfo.proto

namespace Userinfo;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class UserList extends \Google\Protobuf\Internal\Message
{
    private $user_list;

    public function getUserList()
    {
        return $this->user_list;
    }

    public function setUserList(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Userinfo\UserInfo::class);
        $this->user_list = $var;
    }

}

class UserInfo extends \Google\Protobuf\Internal\Message
{
    private $uid = 0;
    private $head = '';
    private $nickname = '';
    private $manager = 0;
    private $recid = 0;

    public function getUid()
    {
        return $this->uid;
    }

    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;
    }

    public function getHead()
    {
        return $this->head;
    }

    public function setHead($var)
    {
        GPBUtil::checkString($var, True);
        $this->head = $var;
    }

    public function getNickname()
    {
        return $this->nickname;
    }

    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;
    }

    public function getManager()
    {
        return $this->manager;
    }

    public function setManager($var)
    {
        GPBUtil::checkUint32($var);
        $this->manager = $var;
    }

    public function getRecid()
    {
        return $this->recid;
    }

    public function setRecid($var)
    {
        GPBUtil::checkUint32($var);
        $this->recid = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aae010a0e75736572696e666f2e70726f746f120875736572696e666f22" .
    "310a08557365724c69737412250a09757365725f6c69737418012003280b" .
    "32122e75736572696e666f2e55736572496e666f22570a0855736572496e" .
    "666f120b0a0375696418012001280d120c0a046865616418022001280912" .
    "100a086e69636b6e616d65180320012809120f0a076d616e616765721804" .
    "2001280d120d0a05726563696418052001280d620670726f746f33"
));

