<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: palyerinfo_php.proto

namespace Foo;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Foo.PlayerInfo</code>
 */
class PlayerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *������
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    private $code = 0;
    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>uint32 uid = 2;</code>
     */
    private $uid = 0;
    /**
     * <pre>
     *�ǳ�
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    private $nickname = '';
    /**
     * <pre>
     *ͷ��
     * </pre>
     *
     * <code>string head_img_url = 4;</code>
     */
    private $head_img_url = '';
    /**
     * <pre>
     *�Ա�,1-Ů��2-��
     * </pre>
     *
     * <code>uint32 sex = 5;</code>
     */
    private $sex = 0;
    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>uint32 roomcard = 6;</code>
     */
    private $roomcard = 0;
    /**
     * <pre>
     *������
     * </pre>
     *
     * <code>int32 bubble = 7;</code>
     */
    private $bubble = 0;
    /**
     * <pre>
     *�������
     * </pre>
     *
     * <code>string passwd = 8;</code>
     */
    private $passwd = '';
    /**
     * <pre>
     *��¼IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    private $ip = '';
    /**
     * <pre>
     *����ID
     * </pre>
     *
     * <code>uint32 room_id = 10;</code>
     */
    private $room_id = 0;
    /**
     * <pre>
     *��ɫID��1-��˾,2-�ͷ�,3-�ܴ���4-����5-���
     * </pre>
     *
     * <code>uint32 rid = 11;</code>
     */
    private $rid = 0;
    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string gatewy = 12;</code>
     */
    private $gatewy = '';
    /**
     * <pre>
     *�����
     * </pre>
     *
     * <code>string pmd = 13;</code>
     */
    private $pmd = '';

    /**
     * <pre>
     *������
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * <pre>
     *������
     * </pre>
     *
     * <code>uint32 code = 1;</code>
     */
    public function setCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->code = $var;
    }

    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>uint32 uid = 2;</code>
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * <pre>
     *���ID
     * </pre>
     *
     * <code>uint32 uid = 2;</code>
     */
    public function setUid($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid = $var;
    }

    /**
     * <pre>
     *�ǳ�
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * <pre>
     *�ǳ�
     * </pre>
     *
     * <code>string nickname = 3;</code>
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;
    }

    /**
     * <pre>
     *ͷ��
     * </pre>
     *
     * <code>string head_img_url = 4;</code>
     */
    public function getHeadImgUrl()
    {
        return $this->head_img_url;
    }

    /**
     * <pre>
     *ͷ��
     * </pre>
     *
     * <code>string head_img_url = 4;</code>
     */
    public function setHeadImgUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->head_img_url = $var;
    }

    /**
     * <pre>
     *�Ա�,1-Ů��2-��
     * </pre>
     *
     * <code>uint32 sex = 5;</code>
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * <pre>
     *�Ա�,1-Ů��2-��
     * </pre>
     *
     * <code>uint32 sex = 5;</code>
     */
    public function setSex($var)
    {
        GPBUtil::checkUint32($var);
        $this->sex = $var;
    }

    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>uint32 roomcard = 6;</code>
     */
    public function getRoomcard()
    {
        return $this->roomcard;
    }

    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>uint32 roomcard = 6;</code>
     */
    public function setRoomcard($var)
    {
        GPBUtil::checkUint32($var);
        $this->roomcard = $var;
    }

    /**
     * <pre>
     *������
     * </pre>
     *
     * <code>int32 bubble = 7;</code>
     */
    public function getBubble()
    {
        return $this->bubble;
    }

    /**
     * <pre>
     *������
     * </pre>
     *
     * <code>int32 bubble = 7;</code>
     */
    public function setBubble($var)
    {
        GPBUtil::checkInt32($var);
        $this->bubble = $var;
    }

    /**
     * <pre>
     *�������
     * </pre>
     *
     * <code>string passwd = 8;</code>
     */
    public function getPasswd()
    {
        return $this->passwd;
    }

    /**
     * <pre>
     *�������
     * </pre>
     *
     * <code>string passwd = 8;</code>
     */
    public function setPasswd($var)
    {
        GPBUtil::checkString($var, True);
        $this->passwd = $var;
    }

    /**
     * <pre>
     *��¼IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * <pre>
     *��¼IP
     * </pre>
     *
     * <code>string ip = 9;</code>
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;
    }

    /**
     * <pre>
     *����ID
     * </pre>
     *
     * <code>uint32 room_id = 10;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <pre>
     *����ID
     * </pre>
     *
     * <code>uint32 room_id = 10;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    /**
     * <pre>
     *��ɫID��1-��˾,2-�ͷ�,3-�ܴ���4-����5-���
     * </pre>
     *
     * <code>uint32 rid = 11;</code>
     */
    public function getRid()
    {
        return $this->rid;
    }

    /**
     * <pre>
     *��ɫID��1-��˾,2-�ͷ�,3-�ܴ���4-����5-���
     * </pre>
     *
     * <code>uint32 rid = 11;</code>
     */
    public function setRid($var)
    {
        GPBUtil::checkUint32($var);
        $this->rid = $var;
    }

    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string gatewy = 12;</code>
     */
    public function getGatewy()
    {
        return $this->gatewy;
    }

    /**
     * <pre>
     *����
     * </pre>
     *
     * <code>string gatewy = 12;</code>
     */
    public function setGatewy($var)
    {
        GPBUtil::checkString($var, True);
        $this->gatewy = $var;
    }

    /**
     * <pre>
     *�����
     * </pre>
     *
     * <code>string pmd = 13;</code>
     */
    public function getPmd()
    {
        return $this->pmd;
    }

    /**
     * <pre>
     *�����
     * </pre>
     *
     * <code>string pmd = 13;</code>
     */
    public function setPmd($var)
    {
        GPBUtil::checkString($var, True);
        $this->pmd = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0afb010a1470616c796572696e666f5f7068702e70726f746f1203466f6f" .
    "22d5010a0a506c61796572496e666f120c0a04636f646518012001280d12" .
    "0b0a0375696418022001280d12100a086e69636b6e616d65180320012809" .
    "12140a0c686561645f696d675f75726c180420012809120b0a0373657818" .
    "052001280d12100a08726f6f6d6361726418062001280d120e0a06627562" .
    "626c65180720012805120e0a06706173737764180820012809120a0a0269" .
    "70180920012809120f0a07726f6f6d5f6964180a2001280d120b0a037269" .
    "64180b2001280d120e0a06676174657779180c20012809120b0a03706d64" .
    "180d20012809620670726f746f33"
));

