<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis_data_php.proto

namespace Foo;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *所有战绩100条
 * </pre>
 *
 * Protobuf type <code>Foo.Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Foo.RecordInfo record_info = 1;</code>
     */
    private $record_info;

    /**
     * <code>repeated .Foo.RecordInfo record_info = 1;</code>
     */
    public function getRecordInfo()
    {
        return $this->record_info;
    }

    /**
     * <code>repeated .Foo.RecordInfo record_info = 1;</code>
     */
    public function setRecordInfo(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Foo\RecordInfo::class);
        $this->record_info = $var;
    }

}

/**
 * <pre>
 *单条战绩
 * </pre>
 *
 * Protobuf type <code>Foo.RecordInfo</code>
 */
class RecordInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    private $room_id = 0;
    /**
     * <pre>
     *局数
     * </pre>
     *
     * <code>uint32 num_game = 2;</code>
     */
    private $num_game = 0;
    /**
     * <pre>
     *玩家1
     * </pre>
     *
     * <code>uint32 uid_one = 3;</code>
     */
    private $uid_one = 0;
    /**
     * <pre>
     *玩家1昵称
     * </pre>
     *
     * <code>string nikename_one = 4;</code>
     */
    private $nikename_one = '';
    /**
     * <pre>
     *玩家1分数
     * </pre>
     *
     * <code>int32 score_sum_one = 5;</code>
     */
    private $score_sum_one = 0;
    /**
     * <pre>
     *玩家2
     * </pre>
     *
     * <code>uint32 uid_two = 6;</code>
     */
    private $uid_two = 0;
    /**
     * <pre>
     *玩家2昵称
     * </pre>
     *
     * <code>string nikename_two = 7;</code>
     */
    private $nikename_two = '';
    /**
     * <pre>
     *玩家2分数
     * </pre>
     *
     * <code>int32 score_sum_two = 8;</code>
     */
    private $score_sum_two = 0;
    /**
     * <pre>
     *玩家3
     * </pre>
     *
     * <code>uint32 uid_three = 9;</code>
     */
    private $uid_three = 0;
    /**
     * <pre>
     *玩家3昵称
     * </pre>
     *
     * <code>string nikename_three = 10;</code>
     */
    private $nikename_three = '';
    /**
     * <pre>
     *玩家3分数
     * </pre>
     *
     * <code>int32 score_sum_three = 11;</code>
     */
    private $score_sum_three = 0;
    /**
     * <pre>
     *玩家4
     * </pre>
     *
     * <code>uint32 uid_four = 12;</code>
     */
    private $uid_four = 0;
    /**
     * <pre>
     *玩家4昵称
     * </pre>
     *
     * <code>string nikename_four = 13;</code>
     */
    private $nikename_four = '';
    /**
     * <pre>
     *玩家4分数
     * </pre>
     *
     * <code>int32 score_sum_four = 14;</code>
     */
    private $score_sum_four = 0;
    /**
     * <pre>
     *开房时间
     * </pre>
     *
     * <code>string create_time = 15;</code>
     */
    private $create_time = '';
    /**
     * <pre>
     *游戏类型
     * </pre>
     *
     * <code>int32 gametype = 16;</code>
     */
    private $gametype = 0;

    /**
     * <pre>
     *房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * <pre>
     *房间号
     * </pre>
     *
     * <code>uint32 room_id = 1;</code>
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint32($var);
        $this->room_id = $var;
    }

    /**
     * <pre>
     *局数
     * </pre>
     *
     * <code>uint32 num_game = 2;</code>
     */
    public function getNumGame()
    {
        return $this->num_game;
    }

    /**
     * <pre>
     *局数
     * </pre>
     *
     * <code>uint32 num_game = 2;</code>
     */
    public function setNumGame($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_game = $var;
    }

    /**
     * <pre>
     *玩家1
     * </pre>
     *
     * <code>uint32 uid_one = 3;</code>
     */
    public function getUidOne()
    {
        return $this->uid_one;
    }

    /**
     * <pre>
     *玩家1
     * </pre>
     *
     * <code>uint32 uid_one = 3;</code>
     */
    public function setUidOne($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_one = $var;
    }

    /**
     * <pre>
     *玩家1昵称
     * </pre>
     *
     * <code>string nikename_one = 4;</code>
     */
    public function getNikenameOne()
    {
        return $this->nikename_one;
    }

    /**
     * <pre>
     *玩家1昵称
     * </pre>
     *
     * <code>string nikename_one = 4;</code>
     */
    public function setNikenameOne($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_one = $var;
    }

    /**
     * <pre>
     *玩家1分数
     * </pre>
     *
     * <code>int32 score_sum_one = 5;</code>
     */
    public function getScoreSumOne()
    {
        return $this->score_sum_one;
    }

    /**
     * <pre>
     *玩家1分数
     * </pre>
     *
     * <code>int32 score_sum_one = 5;</code>
     */
    public function setScoreSumOne($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_sum_one = $var;
    }

    /**
     * <pre>
     *玩家2
     * </pre>
     *
     * <code>uint32 uid_two = 6;</code>
     */
    public function getUidTwo()
    {
        return $this->uid_two;
    }

    /**
     * <pre>
     *玩家2
     * </pre>
     *
     * <code>uint32 uid_two = 6;</code>
     */
    public function setUidTwo($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_two = $var;
    }

    /**
     * <pre>
     *玩家2昵称
     * </pre>
     *
     * <code>string nikename_two = 7;</code>
     */
    public function getNikenameTwo()
    {
        return $this->nikename_two;
    }

    /**
     * <pre>
     *玩家2昵称
     * </pre>
     *
     * <code>string nikename_two = 7;</code>
     */
    public function setNikenameTwo($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_two = $var;
    }

    /**
     * <pre>
     *玩家2分数
     * </pre>
     *
     * <code>int32 score_sum_two = 8;</code>
     */
    public function getScoreSumTwo()
    {
        return $this->score_sum_two;
    }

    /**
     * <pre>
     *玩家2分数
     * </pre>
     *
     * <code>int32 score_sum_two = 8;</code>
     */
    public function setScoreSumTwo($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_sum_two = $var;
    }

    /**
     * <pre>
     *玩家3
     * </pre>
     *
     * <code>uint32 uid_three = 9;</code>
     */
    public function getUidThree()
    {
        return $this->uid_three;
    }

    /**
     * <pre>
     *玩家3
     * </pre>
     *
     * <code>uint32 uid_three = 9;</code>
     */
    public function setUidThree($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_three = $var;
    }

    /**
     * <pre>
     *玩家3昵称
     * </pre>
     *
     * <code>string nikename_three = 10;</code>
     */
    public function getNikenameThree()
    {
        return $this->nikename_three;
    }

    /**
     * <pre>
     *玩家3昵称
     * </pre>
     *
     * <code>string nikename_three = 10;</code>
     */
    public function setNikenameThree($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_three = $var;
    }

    /**
     * <pre>
     *玩家3分数
     * </pre>
     *
     * <code>int32 score_sum_three = 11;</code>
     */
    public function getScoreSumThree()
    {
        return $this->score_sum_three;
    }

    /**
     * <pre>
     *玩家3分数
     * </pre>
     *
     * <code>int32 score_sum_three = 11;</code>
     */
    public function setScoreSumThree($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_sum_three = $var;
    }

    /**
     * <pre>
     *玩家4
     * </pre>
     *
     * <code>uint32 uid_four = 12;</code>
     */
    public function getUidFour()
    {
        return $this->uid_four;
    }

    /**
     * <pre>
     *玩家4
     * </pre>
     *
     * <code>uint32 uid_four = 12;</code>
     */
    public function setUidFour($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_four = $var;
    }

    /**
     * <pre>
     *玩家4昵称
     * </pre>
     *
     * <code>string nikename_four = 13;</code>
     */
    public function getNikenameFour()
    {
        return $this->nikename_four;
    }

    /**
     * <pre>
     *玩家4昵称
     * </pre>
     *
     * <code>string nikename_four = 13;</code>
     */
    public function setNikenameFour($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_four = $var;
    }

    /**
     * <pre>
     *玩家4分数
     * </pre>
     *
     * <code>int32 score_sum_four = 14;</code>
     */
    public function getScoreSumFour()
    {
        return $this->score_sum_four;
    }

    /**
     * <pre>
     *玩家4分数
     * </pre>
     *
     * <code>int32 score_sum_four = 14;</code>
     */
    public function setScoreSumFour($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_sum_four = $var;
    }

    /**
     * <pre>
     *开房时间
     * </pre>
     *
     * <code>string create_time = 15;</code>
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * <pre>
     *开房时间
     * </pre>
     *
     * <code>string create_time = 15;</code>
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_time = $var;
    }

    /**
     * <pre>
     *游戏类型
     * </pre>
     *
     * <code>int32 gametype = 16;</code>
     */
    public function getGametype()
    {
        return $this->gametype;
    }

    /**
     * <pre>
     *游戏类型
     * </pre>
     *
     * <code>int32 gametype = 16;</code>
     */
    public function setGametype($var)
    {
        GPBUtil::checkInt32($var);
        $this->gametype = $var;
    }

}

/**
 * <pre>
 *大局战绩
 * </pre>
 *
 * Protobuf type <code>Foo.BigRecord</code>
 */
class BigRecord extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Foo.BigRecordInfo bigrecord_info = 1;</code>
     */
    private $bigrecord_info;

    /**
     * <code>repeated .Foo.BigRecordInfo bigrecord_info = 1;</code>
     */
    public function getBigrecordInfo()
    {
        return $this->bigrecord_info;
    }

    /**
     * <code>repeated .Foo.BigRecordInfo bigrecord_info = 1;</code>
     */
    public function setBigrecordInfo(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Foo\BigRecordInfo::class);
        $this->bigrecord_info = $var;
    }

}

/**
 * <pre>
 *小局战绩
 * </pre>
 *
 * Protobuf type <code>Foo.BigRecordInfo</code>
 */
class BigRecordInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *第几局
     * </pre>
     *
     * <code>uint32 indexs = 1;</code>
     */
    private $indexs = 0;
    /**
     * <pre>
     *玩家1
     * </pre>
     *
     * <code>uint32 uid_one = 2;</code>
     */
    private $uid_one = 0;
    /**
     * <pre>
     *玩家1昵称
     * </pre>
     *
     * <code>string nikename_one = 3;</code>
     */
    private $nikename_one = '';
    /**
     * <pre>
     *玩家1分数
     * </pre>
     *
     * <code>int32 score_one = 4;</code>
     */
    private $score_one = 0;
    /**
     * <pre>
     *玩家2
     * </pre>
     *
     * <code>uint32 uid_two = 5;</code>
     */
    private $uid_two = 0;
    /**
     * <pre>
     *玩家2昵称
     * </pre>
     *
     * <code>string nikename_two = 6;</code>
     */
    private $nikename_two = '';
    /**
     * <pre>
     *玩家2分数
     * </pre>
     *
     * <code>int32 score_two = 7;</code>
     */
    private $score_two = 0;
    /**
     * <pre>
     *玩家3
     * </pre>
     *
     * <code>uint32 uid_three = 8;</code>
     */
    private $uid_three = 0;
    /**
     * <pre>
     *玩家3昵称
     * </pre>
     *
     * <code>string nikename_three = 9;</code>
     */
    private $nikename_three = '';
    /**
     * <pre>
     *玩家3分数
     * </pre>
     *
     * <code>int32 score_three = 10;</code>
     */
    private $score_three = 0;
    /**
     * <pre>
     *玩家4
     * </pre>
     *
     * <code>uint32 uid_four = 11;</code>
     */
    private $uid_four = 0;
    /**
     * <pre>
     *玩家4昵称
     * </pre>
     *
     * <code>string nikename_four = 12;</code>
     */
    private $nikename_four = '';
    /**
     * <pre>
     *玩家4分数
     * </pre>
     *
     * <code>int32 score_four = 13;</code>
     */
    private $score_four = 0;
    /**
     * <pre>
     *回访数据
     * </pre>
     *
     * <code>string playback = 14;</code>
     */
    private $playback = '';
    /**
     * <pre>
     *开房时间
     * </pre>
     *
     * <code>string create_time = 15;</code>
     */
    private $create_time = '';
    /**
     * <pre>
     *结束时间
     * </pre>
     *
     * <code>string end_time = 16;</code>
     */
    private $end_time = '';

    /**
     * <pre>
     *第几局
     * </pre>
     *
     * <code>uint32 indexs = 1;</code>
     */
    public function getIndexs()
    {
        return $this->indexs;
    }

    /**
     * <pre>
     *第几局
     * </pre>
     *
     * <code>uint32 indexs = 1;</code>
     */
    public function setIndexs($var)
    {
        GPBUtil::checkUint32($var);
        $this->indexs = $var;
    }

    /**
     * <pre>
     *玩家1
     * </pre>
     *
     * <code>uint32 uid_one = 2;</code>
     */
    public function getUidOne()
    {
        return $this->uid_one;
    }

    /**
     * <pre>
     *玩家1
     * </pre>
     *
     * <code>uint32 uid_one = 2;</code>
     */
    public function setUidOne($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_one = $var;
    }

    /**
     * <pre>
     *玩家1昵称
     * </pre>
     *
     * <code>string nikename_one = 3;</code>
     */
    public function getNikenameOne()
    {
        return $this->nikename_one;
    }

    /**
     * <pre>
     *玩家1昵称
     * </pre>
     *
     * <code>string nikename_one = 3;</code>
     */
    public function setNikenameOne($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_one = $var;
    }

    /**
     * <pre>
     *玩家1分数
     * </pre>
     *
     * <code>int32 score_one = 4;</code>
     */
    public function getScoreOne()
    {
        return $this->score_one;
    }

    /**
     * <pre>
     *玩家1分数
     * </pre>
     *
     * <code>int32 score_one = 4;</code>
     */
    public function setScoreOne($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_one = $var;
    }

    /**
     * <pre>
     *玩家2
     * </pre>
     *
     * <code>uint32 uid_two = 5;</code>
     */
    public function getUidTwo()
    {
        return $this->uid_two;
    }

    /**
     * <pre>
     *玩家2
     * </pre>
     *
     * <code>uint32 uid_two = 5;</code>
     */
    public function setUidTwo($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_two = $var;
    }

    /**
     * <pre>
     *玩家2昵称
     * </pre>
     *
     * <code>string nikename_two = 6;</code>
     */
    public function getNikenameTwo()
    {
        return $this->nikename_two;
    }

    /**
     * <pre>
     *玩家2昵称
     * </pre>
     *
     * <code>string nikename_two = 6;</code>
     */
    public function setNikenameTwo($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_two = $var;
    }

    /**
     * <pre>
     *玩家2分数
     * </pre>
     *
     * <code>int32 score_two = 7;</code>
     */
    public function getScoreTwo()
    {
        return $this->score_two;
    }

    /**
     * <pre>
     *玩家2分数
     * </pre>
     *
     * <code>int32 score_two = 7;</code>
     */
    public function setScoreTwo($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_two = $var;
    }

    /**
     * <pre>
     *玩家3
     * </pre>
     *
     * <code>uint32 uid_three = 8;</code>
     */
    public function getUidThree()
    {
        return $this->uid_three;
    }

    /**
     * <pre>
     *玩家3
     * </pre>
     *
     * <code>uint32 uid_three = 8;</code>
     */
    public function setUidThree($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_three = $var;
    }

    /**
     * <pre>
     *玩家3昵称
     * </pre>
     *
     * <code>string nikename_three = 9;</code>
     */
    public function getNikenameThree()
    {
        return $this->nikename_three;
    }

    /**
     * <pre>
     *玩家3昵称
     * </pre>
     *
     * <code>string nikename_three = 9;</code>
     */
    public function setNikenameThree($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_three = $var;
    }

    /**
     * <pre>
     *玩家3分数
     * </pre>
     *
     * <code>int32 score_three = 10;</code>
     */
    public function getScoreThree()
    {
        return $this->score_three;
    }

    /**
     * <pre>
     *玩家3分数
     * </pre>
     *
     * <code>int32 score_three = 10;</code>
     */
    public function setScoreThree($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_three = $var;
    }

    /**
     * <pre>
     *玩家4
     * </pre>
     *
     * <code>uint32 uid_four = 11;</code>
     */
    public function getUidFour()
    {
        return $this->uid_four;
    }

    /**
     * <pre>
     *玩家4
     * </pre>
     *
     * <code>uint32 uid_four = 11;</code>
     */
    public function setUidFour($var)
    {
        GPBUtil::checkUint32($var);
        $this->uid_four = $var;
    }

    /**
     * <pre>
     *玩家4昵称
     * </pre>
     *
     * <code>string nikename_four = 12;</code>
     */
    public function getNikenameFour()
    {
        return $this->nikename_four;
    }

    /**
     * <pre>
     *玩家4昵称
     * </pre>
     *
     * <code>string nikename_four = 12;</code>
     */
    public function setNikenameFour($var)
    {
        GPBUtil::checkString($var, True);
        $this->nikename_four = $var;
    }

    /**
     * <pre>
     *玩家4分数
     * </pre>
     *
     * <code>int32 score_four = 13;</code>
     */
    public function getScoreFour()
    {
        return $this->score_four;
    }

    /**
     * <pre>
     *玩家4分数
     * </pre>
     *
     * <code>int32 score_four = 13;</code>
     */
    public function setScoreFour($var)
    {
        GPBUtil::checkInt32($var);
        $this->score_four = $var;
    }

    /**
     * <pre>
     *回访数据
     * </pre>
     *
     * <code>string playback = 14;</code>
     */
    public function getPlayback()
    {
        return $this->playback;
    }

    /**
     * <pre>
     *回访数据
     * </pre>
     *
     * <code>string playback = 14;</code>
     */
    public function setPlayback($var)
    {
        GPBUtil::checkString($var, True);
        $this->playback = $var;
    }

    /**
     * <pre>
     *开房时间
     * </pre>
     *
     * <code>string create_time = 15;</code>
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * <pre>
     *开房时间
     * </pre>
     *
     * <code>string create_time = 15;</code>
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_time = $var;
    }

    /**
     * <pre>
     *结束时间
     * </pre>
     *
     * <code>string end_time = 16;</code>
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * <pre>
     *结束时间
     * </pre>
     *
     * <code>string end_time = 16;</code>
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;
    }

}

/**
 * <pre>
 *玩家房卡信息
 * </pre>
 *
 * Protobuf type <code>Foo.PlayerInfo</code>
 */
class PlayerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *房卡数
     * </pre>
     *
     * <code>uint32 card_num = 1;</code>
     */
    private $card_num = 0;
    /**
     * <pre>
     *泡泡币数
     * </pre>
     *
     * <code>int32 bubble_num = 2;</code>
     */
    private $bubble_num = 0;
    /**
     * <pre>
     *玩家角色ID
     * </pre>
     *
     * <code>uint32 role_id = 3;</code>
     */
    private $role_id = 0;
    /**
     * <pre>
     *8局消耗房卡
     * </pre>
     *
     * <code>uint32 baju_num = 4;</code>
     */
    private $baju_num = 0;
    /**
     * <pre>
     *16局消耗房卡
     * </pre>
     *
     * <code>uint32 shiliu_num = 5;</code>
     */
    private $shiliu_num = 0;
    /**
     * <pre>
     *跑马灯信息
     * </pre>
     *
     * <code>string paoma = 6;</code>
     */
    private $paoma = '';

    /**
     * <pre>
     *房卡数
     * </pre>
     *
     * <code>uint32 card_num = 1;</code>
     */
    public function getCardNum()
    {
        return $this->card_num;
    }

    /**
     * <pre>
     *房卡数
     * </pre>
     *
     * <code>uint32 card_num = 1;</code>
     */
    public function setCardNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->card_num = $var;
    }

    /**
     * <pre>
     *泡泡币数
     * </pre>
     *
     * <code>int32 bubble_num = 2;</code>
     */
    public function getBubbleNum()
    {
        return $this->bubble_num;
    }

    /**
     * <pre>
     *泡泡币数
     * </pre>
     *
     * <code>int32 bubble_num = 2;</code>
     */
    public function setBubbleNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->bubble_num = $var;
    }

    /**
     * <pre>
     *玩家角色ID
     * </pre>
     *
     * <code>uint32 role_id = 3;</code>
     */
    public function getRoleId()
    {
        return $this->role_id;
    }

    /**
     * <pre>
     *玩家角色ID
     * </pre>
     *
     * <code>uint32 role_id = 3;</code>
     */
    public function setRoleId($var)
    {
        GPBUtil::checkUint32($var);
        $this->role_id = $var;
    }

    /**
     * <pre>
     *8局消耗房卡
     * </pre>
     *
     * <code>uint32 baju_num = 4;</code>
     */
    public function getBajuNum()
    {
        return $this->baju_num;
    }

    /**
     * <pre>
     *8局消耗房卡
     * </pre>
     *
     * <code>uint32 baju_num = 4;</code>
     */
    public function setBajuNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->baju_num = $var;
    }

    /**
     * <pre>
     *16局消耗房卡
     * </pre>
     *
     * <code>uint32 shiliu_num = 5;</code>
     */
    public function getShiliuNum()
    {
        return $this->shiliu_num;
    }

    /**
     * <pre>
     *16局消耗房卡
     * </pre>
     *
     * <code>uint32 shiliu_num = 5;</code>
     */
    public function setShiliuNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->shiliu_num = $var;
    }

    /**
     * <pre>
     *跑马灯信息
     * </pre>
     *
     * <code>string paoma = 6;</code>
     */
    public function getPaoma()
    {
        return $this->paoma;
    }

    /**
     * <pre>
     *跑马灯信息
     * </pre>
     *
     * <code>string paoma = 6;</code>
     */
    public function setPaoma($var)
    {
        GPBUtil::checkString($var, True);
        $this->paoma = $var;
    }

}

/**
 * <pre>
 *我的群
 * </pre>
 *
 * Protobuf type <code>Foo.GroupList</code>
 */
class GroupList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Foo.MyGroup mygroup_list = 1;</code>
     */
    private $mygroup_list;

    /**
     * <code>repeated .Foo.MyGroup mygroup_list = 1;</code>
     */
    public function getMygroupList()
    {
        return $this->mygroup_list;
    }

    /**
     * <code>repeated .Foo.MyGroup mygroup_list = 1;</code>
     */
    public function setMygroupList(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Foo\MyGroup::class);
        $this->mygroup_list = $var;
    }

}

/**
 * Protobuf type <code>Foo.MyGroup</code>
 */
class MyGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>uint32 group_id = 1;</code>
     */
    private $group_id = 0;
    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string group_name = 2;</code>
     */
    private $group_name = '';
    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>uint32 group_main = 3;</code>
     */
    private $group_main = 0;
    /**
     * <pre>
     *群主昵称
     * </pre>
     *
     * <code>string group_nickname = 4;</code>
     */
    private $group_nickname = '';
    /**
     * <pre>
     *群人数
     * </pre>
     *
     * <code>uint32 group_num = 5;</code>
     */
    private $group_num = 0;

    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>uint32 group_id = 1;</code>
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>uint32 group_id = 1;</code>
     */
    public function setGroupId($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_id = $var;
    }

    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string group_name = 2;</code>
     */
    public function getGroupName()
    {
        return $this->group_name;
    }

    /**
     * <pre>
     *群名称
     * </pre>
     *
     * <code>string group_name = 2;</code>
     */
    public function setGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_name = $var;
    }

    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>uint32 group_main = 3;</code>
     */
    public function getGroupMain()
    {
        return $this->group_main;
    }

    /**
     * <pre>
     *群主ID
     * </pre>
     *
     * <code>uint32 group_main = 3;</code>
     */
    public function setGroupMain($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_main = $var;
    }

    /**
     * <pre>
     *群主昵称
     * </pre>
     *
     * <code>string group_nickname = 4;</code>
     */
    public function getGroupNickname()
    {
        return $this->group_nickname;
    }

    /**
     * <pre>
     *群主昵称
     * </pre>
     *
     * <code>string group_nickname = 4;</code>
     */
    public function setGroupNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_nickname = $var;
    }

    /**
     * <pre>
     *群人数
     * </pre>
     *
     * <code>uint32 group_num = 5;</code>
     */
    public function getGroupNum()
    {
        return $this->group_num;
    }

    /**
     * <pre>
     *群人数
     * </pre>
     *
     * <code>uint32 group_num = 5;</code>
     */
    public function setGroupNum($var)
    {
        GPBUtil::checkUint32($var);
        $this->group_num = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0acd080a1472656469735f646174615f7068702e70726f746f1203466f6f" .
    "222e0a065265636f726412240a0b7265636f72645f696e666f1801200328" .
    "0b320f2e466f6f2e5265636f7264496e666f22d7020a0a5265636f726449" .
    "6e666f120f0a07726f6f6d5f696418012001280d12100a086e756d5f6761" .
    "6d6518022001280d120f0a077569645f6f6e6518032001280d12140a0c6e" .
    "696b656e616d655f6f6e6518042001280912150a0d73636f72655f73756d" .
    "5f6f6e65180520012805120f0a077569645f74776f18062001280d12140a" .
    "0c6e696b656e616d655f74776f18072001280912150a0d73636f72655f73" .
    "756d5f74776f18082001280512110a097569645f74687265651809200128" .
    "0d12160a0e6e696b656e616d655f7468726565180a2001280912170a0f73" .
    "636f72655f73756d5f7468726565180b2001280512100a087569645f666f" .
    "7572180c2001280d12150a0d6e696b656e616d655f666f7572180d200128" .
    "0912160a0e73636f72655f73756d5f666f7572180e2001280512130a0b63" .
    "72656174655f74696d65180f2001280912100a0867616d65747970651810" .
    "2001280522370a094269675265636f7264122a0a0e6269677265636f7264" .
    "5f696e666f18012003280b32122e466f6f2e4269675265636f7264496e66" .
    "6f22c9020a0d4269675265636f7264496e666f120e0a06696e6465787318" .
    "012001280d120f0a077569645f6f6e6518022001280d12140a0c6e696b65" .
    "6e616d655f6f6e6518032001280912110a0973636f72655f6f6e65180420" .
    "012805120f0a077569645f74776f18052001280d12140a0c6e696b656e61" .
    "6d655f74776f18062001280912110a0973636f72655f74776f1807200128" .
    "0512110a097569645f746872656518082001280d12160a0e6e696b656e61" .
    "6d655f746872656518092001280912130a0b73636f72655f746872656518" .
    "0a2001280512100a087569645f666f7572180b2001280d12150a0d6e696b" .
    "656e616d655f666f7572180c2001280912120a0a73636f72655f666f7572" .
    "180d2001280512100a08706c61796261636b180e2001280912130a0b6372" .
    "656174655f74696d65180f2001280912100a08656e645f74696d65181020" .
    "01280922780a0a506c61796572496e666f12100a08636172645f6e756d18" .
    "012001280d12120a0a627562626c655f6e756d180220012805120f0a0772" .
    "6f6c655f696418032001280d12100a0862616a755f6e756d18042001280d" .
    "12120a0a7368696c69755f6e756d18052001280d120d0a0570616f6d6118" .
    "0620012809222f0a0947726f75704c69737412220a0c6d7967726f75705f" .
    "6c69737418012003280b320c2e466f6f2e4d7947726f7570226e0a074d79" .
    "47726f757012100a0867726f75705f696418012001280d12120a0a67726f" .
    "75705f6e616d6518022001280912120a0a67726f75705f6d61696e180320" .
    "01280d12160a0e67726f75705f6e69636b6e616d6518042001280912110a" .
    "0967726f75705f6e756d18052001280d620670726f746f33"
));

